<a href="https://colab.research.google.com/github/smlra-kjsce/ML-DL101/blob/master/Gradient_Descent_from_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

class NeuralNetwork:
  def __init__(self):
    np.random.seed(42)
    self.Wij = np.random.rand(4,5)
    self.Wjk = np.random.rand(5,1)

  def sigmoid(self, x, w):
    z = np.dot(x,w)
    return 1/(1 + np.exp(-z))
  
  def diff_sigmoid(self, x, w):
    return self.sigmoid(x,w)*(1-self.sigmoid(x,w))
  
  def gradient_descent(self,x,y, epochs):
    for i in range(epochs):
      Xi = x #Input layer
      Xj = self.sigmoid(Xi, self.Wij) #Hidden layer
      Y_cap = self.sigmoid(Xj, self.Wjk) #Final layer
      grad_Wjk = np.dot(Xj.T, (y-Y_cap)*self.diff_sigmoid(Xj, self.Wjk))
      grad_Wij = np.dot(Xi.T, np.dot((y-Y_cap)* self.diff_sigmoid(Xj, self.Wjk), self.Wjk.T) * self.diff_sigmoid(Xi, self.Wij))

      self.Wjk += grad_Wjk
      self.Wij += grad_Wij

    print('The final prediction from neural network are: ')
    print(Y_cap)

In [18]:
if __name__ == '__main__':
    NN = NeuralNetwork()
    print('Random starting input to hidden weights: ')
    print(NN.Wij)
    print('Random starting hidden to output weights: ')
    print(NN.Wjk)
    X = np.array([[0, 0, 1, 1], [1, 1, 0, 1], [1, 0, 1, 1], [0, 1, 0, 1], [0, 0, 0, 1]])
    y = np.array([[0, 1, 1, 0, 1]]).T
    neural_network.gradient_descent(X, y, 10000)

Random starting input to hidden weights: 
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]]
Random starting hidden to output weights: 
[[0.61185289]
 [0.13949386]
 [0.29214465]
 [0.36636184]
 [0.45606998]]
The final prediction from neural network are: 
[[0.00589178]
 [0.99658221]
 [0.99669157]
 [0.00609915]
 [0.99361295]]
